### ISSUE TITLE
[Enhancement] Send filename, plus code inside of an embed

### ISSUE THREAD

**Issue by alii** [LukWebsForge/HasteIt#14]
I think sending the code inside of an embed, along with sending the name of the file will make the plugin much nicer to use and share code with other people. Code blocks are still supported in an Embed Description, and the title of the embed could simply be the filename (with the footer saying Discord Beam, allowing for avatar and username to be customized - you still get branding!)

**Comment by lukbukkit** [comment]
Thanks a lot for this nice idea. If I've got some spare time, I'll try to implement this.

A note about the avatar: I just haven't had the time to implement the setting for the avatar url properly and test it extensively (see issue #7). But your idea to put name into the footer is a good suggestion.

**Comment by alii** [comment]
Would be awesome! I can't wait to see what you come up with :)

I would contribute but unfortunately, I'm a JS/TS dev. I don't know Java :(

**Comment by lukbukkit** [comment]
I took a little of my time and implemented this feature.

I've created an embedment for every action. You can view screenshots of the embedments on imgur: https://imgur.com/a/8OeVMhN. You are able to customize your user name and add an url for an user icon. I no longer modify the webhook's name and image.

If you want to help and test this feature, here's pre-relase version of the plugin: 
[DiscordBeam-1.06.zip](https://github.com/LukWebsForge/ShareIt/files/4496778/DiscordBeam-1.06.zip)

Again, Thanks for this good idea. 👍

**Comment by alii** [comment]
Woohoo! I'll give it a whirl

**Comment by alii** [comment]
Absolutely perfect! Thanks so much for this! I'll be using this a lot I think

![image](https://user-images.githubusercontent.com/25351731/79672081-ca8d7f80-81c6-11ea-90d9-c37152f12e78.png)

**Comment by alii** [comment]
I have discovered an issue, apologies for the many messages here. You can type "```" inside a file and it will escape the codeblock, allowing for text *outside* of the codeblock in the embed.
![image](https://user-images.githubusercontent.com/25351731/79672146-5bfcf180-81c7-11ea-8f64-a8c2835687a3.png)

**Comment by lukbukkit** [comment]
Sadly Discord doesn't provide any way to escape the triple backtick (or at least I don't know it) and I don't want to meddle with the code which will be shared.
So I guess the best way to prevent this, is to share this code via an other service (including Discord file) or do you've got any other ideas?

**Comment by alii** [comment]
That's a great point. Okay, I think this is the best way then. Great work

**Comment by lukbukkit** [comment]
Here's the updated version, which uploads the file if it contains three or more backticks in a row: [DiscordBeam-1.06.zip](https://github.com/LukWebsForge/ShareIt/files/4505544/DiscordBeam-1.06.zip)

**Comment by lukbukkit** [comment]
Maybe I should add a message which explains why the file can't be shared via a Discord message.

**Comment by lukbukkit** [comment]
I've added the additional message to the plugin and I'm going to test the plugin for a few days, then release it to the JetBrains plugin repository. 👍

**Comment by lukbukkit** [comment]
Finally I got time to release the latest version to the JetBrains marketplace. The plugin should be available in about 2 or 3 days.
