### ISSUE TITLE
[suggestion] a way to donate.

### ISSUE THREAD

**Issue by SobieskiCodes** [LukWebsForge/HasteIt#17]
I appreciate this project and use it daily, please put up a way to at least buy you a coffee or beer.

**Comment by lukbukkit** [comment]
Thanks for your idea. I'm already happy, that people use the stuff we built. :)
Based on your suggestion, I've added a PayPal link to the [main GitHub page](https://github.com/LukWebsForge/ShareIt) of this project.
If you want to support me and my work, you can donate using it.
