### ISSUE TITLE
intellij idea 2021.3.2 (Ultimate) discordbeam-1.20.2.jar 1.20.2 Mac Pro doesn't work

### ISSUE THREAD

**Issue by vvladovskiy** [LukWebsForge/HasteIt#18]
After install PlugIn give me an error, cant ran Intellij at all. please help!

**Comment by lukbukkit** [comment]
Hey, thanks for creating the issue. Can you provide me with an error of some sort?

**Comment by vvladovskiy** [comment]
Hi,
Thanks for your reply. I figure out how to fix it. Works fine now.
Upgrade to .3 both Beam and IIntellij helps.
Thanks again.
Vick

**Comment by lukbukkit** [comment]
I'm glad to hear that.
