### ISSUE TITLE
Possibility to set custom URL to haste-server instance

### ISSUE THREAD

**Issue by SebastianTroc** [LukWebsForge/HasteIt#2]
Is there a possibility to set custom URL to self-hosted haste-server instance?

**Comment by lukbukkit** [comment]
Currently not, but I can implement this functionality. I'll keep you updated.

**Comment by lukbukkit** [comment]
I've add a setting to use a custom url in the [latest commit](https://github.com/LukWebsForge/HasteIt/commit/8ba28c133df4149b2175f83396cdcf51e7bee31e). 
It should work, but I have to test it in detail tomorrow.
If you want to try it early and provide feedback, here's the [build](https://drive.google.com/file/d/1gXd_KcfprvtKJlE8rAkJUDd8h1ieY3Xj/view?usp=sharing) of the commit.

**Comment by SebastianTroc** [comment]
It works nice, thank you :)

**Comment by lukbukkit** [comment]
The version 1.06 is now also available via the JetBrains plugin repository.
