### ISSUE TITLE
Upload entire file

### ISSUE THREAD

**Issue by Huddlect** [LukWebsForge/HasteIt#3]
It would be useful to be able to upload an entire file by right-clicking without selection and right-clicking on a file. Both also contain a Gist button.

**Comment by lukbukkit** [comment]
Good idea 👍 I'll start working on it soon

**Comment by lukbukkit** [comment]
Everything is implemented, I'll release it tomorrow.

**Comment by lukbukkit** [comment]
You can now download the update via the [Jetbrains Plugin Repository](https://plugins.jetbrains.com/plugin/8488-hasteit).
