### ISSUE TITLE
Upload entire file via tab menu

### ISSUE THREAD

**Issue by Huddlect** [LukWebsForge/HasteIt#4]
In my previous issue #3 I forgot to mention that there's also a Gist button in the tab rightclick menu where you also might want to add a Haste button.
Thanks for implementing my previuous suggestion.

**Comment by lukbukkit** [comment]
Thanks for the report. 
Can you send me a screenshot of where the Haste button is missing?
Sorry I can't find it. ):

**Comment by Huddlect** [comment]
https://prntscr.com/moazqk
