### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by lukbukkit** [LukWebsForge/HasteIt#5]
The new Discord Integration called DiscordBeam for IDEA-based IDEs is now ready for testing.

Just download the .zip file and drag n' drop it onto your IDE.
[DiscordBeam-1.01.zip](https://github.com/LukWebsForge/HasteIt/files/3435600/DiscordBeam-1.01.zip)

To use the plugin, just right click onto a file in the project panel or right click in an editor window and select *Beam to Discord*

Thanks @SobieskiCodes for the idea!

**Comment by SobieskiCodes** [comment]
Flawless so far, thank you!

**Comment by SobieskiCodes** [comment]
Not sure if it'd be useful for others - but I'd find it helpful to be able to store multiple url's. Still no bugs/issues that I've come across.

**Comment by lukbukkit** [comment]
Thanks for testing and that's a good idea! 
I guess I'll release the plugin first and then work on the multiple urls :+1:

**Comment by lukbukkit** [comment]
The plugin still has to be confirmed by JetBrains, but here's the link to the plugin page: https://plugins.jetbrains.com/plugin/12804-discordbeam

**Comment by lukbukkit** [comment]
The plugin was approved by JetBrains and can be downloaded via your IDE.
