### ISSUE TITLE
Hastebin as a service for sharing large files

### ISSUE THREAD

**Issue by lukbukkit** [LukWebsForge/HasteIt#9]
Add https://hastebin.com/ as a service for sharing large files.
If the HasteIt plugin is also installed, the service should use its settings.

Idea: #6 @SobieskiCodes

**Comment by SobieskiCodes** [comment]
![image](https://user-images.githubusercontent.com/12957753/83544227-94346700-a4cb-11ea-969a-790a2d65bcda.png)
Can't seem to use hasteit with the newest build of discordbeam.
This is a fresh install of the newest pycharm community, the newest hasteit and discordbeam.
Hasteit is set to a custom URL
Windows 10 build 2004 if that's of any use to you.
@LukBukkit

**Comment by lukbukkit** [comment]
Thanks I'll look into it this or next weekend.

**Comment by lukbukkit** [comment]
Okay I was a little bit curious and tried to reproduce this error, but I was unable to do it. Please check, that all updates for both plugins are installed.

Does the error always occur or just sometimes?

Here the are versions of PyCharm and my plugins, which I used to reproduce this problem.

![grafik](https://user-images.githubusercontent.com/8070210/83553407-725ad480-a50b-11ea-993c-149c8a1e720a.png)

![grafik](https://user-images.githubusercontent.com/8070210/83553440-7f77c380-a50b-11ea-852f-e8fb2e76711a.png)

The only difference is, that I'm using Windows 1909, maybe this could be the cause, but I don't know why it should. 🤔

**Comment by SobieskiCodes** [comment]
It's now working of course because I bugged you (i don't know which fixed it, i uninstalled pycharm deleting the appdata folder, rebooted installed).
It was EVERY TIME (granted I've only been on this setup for 2 days, so...less than 5 times). 
I did install Discord Beam before Hasteit, curious if it was a chacheing issue? Either way, sorry for wasting your time should have tried more things first.

edit: Same versions of everything except windows incase it comes up in the future.
I did install wsl2 during this windows install too, not that I think it matters, just more info incase.

**Comment by lukbukkit** [comment]
I'm glad to hear that it works now. And it's no problem, that you did notify me, to the contrary I did find another bug while searching for your problem.

**Comment by SobieskiCodes** [comment]
did it happen to be the blank message? Im not sure how to fix this one ha.
It appears message is blank.

> java.io.IOException while uploading: Unexpected code Response{protocol=h2, code=400, message=, url=https://discordapp.com/api/webhooks/my_actual_hook_link}

**Comment by lukbukkit** [comment]
This is the problem that I fixed with the latest update. Embeds only allow up 1024 characters and I did allow more, so Discord throws an 400 error.

**Comment by SobieskiCodes** [comment]
Thanks, I really appreciate the time and effort you put into this project. It make's life so easy in the coding support servers. Will wait for it to be approved.
